// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "Realiza autenticação de membro na API e retorna token de autenticação.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "autenticação"
                ],
                "summary": "Autenticação de membro.",
                "parameters": [
                    {
                        "description": "Credenciais de login",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReqAutenticacaoDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResAutenticacaoDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErroDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ErroDTO": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "integer"
                },
                "detalhes": {
                    "type": "string"
                },
                "mensagem": {
                    "type": "string"
                }
            }
        },
        "dto.MembroDTO": {
            "type": "object",
            "properties": {
                "celular": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "matricula": {
                    "type": "string"
                },
                "membro_id": {
                    "type": "integer"
                },
                "nome_completo": {
                    "type": "string"
                },
                "nome_usuario": {
                    "type": "string"
                }
            }
        },
        "dto.ReqAutenticacaoDTO": {
            "type": "object",
            "required": [
                "nome_usuario",
                "senha"
            ],
            "properties": {
                "nome_usuario": {
                    "type": "string"
                },
                "senha": {
                    "type": "string"
                }
            }
        },
        "dto.ResAutenticacaoDTO": {
            "type": "object",
            "properties": {
                "cargo": {
                    "type": "string"
                },
                "membro": {
                    "$ref": "#/definitions/dto.MembroDTO"
                },
                "token": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/spe/api/v1",
	Schemes:          []string{},
	Title:            "SPE API",
	Description:      "API do Sistema de Ponto Eletrônico - SPE",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
