basePath: /spe/api/v1
definitions:
  dto.ErroDTO:
    properties:
      codigo:
        type: integer
      detalhes:
        type: string
      mensagem:
        type: string
    type: object
  dto.MembroDTO:
    properties:
      celular:
        type: string
      email:
        type: string
      matricula:
        type: string
      membro_id:
        type: integer
      nome_completo:
        type: string
      nome_usuario:
        type: string
    type: object
  dto.ReqAutenticacaoDTO:
    properties:
      nome_usuario:
        type: string
      senha:
        type: string
    required:
    - nome_usuario
    - senha
    type: object
  dto.ResAutenticacaoDTO:
    properties:
      cargo:
        type: string
      membro:
        $ref: '#/definitions/dto.MembroDTO'
      token:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API do Sistema de Ponto Eletrônico - SPE
  title: SPE API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Realiza autenticação de membro na API e retorna token de autenticação.
      parameters:
      - description: Credenciais de login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ReqAutenticacaoDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResAutenticacaoDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErroDTO'
      summary: Autenticação de membro.
      tags:
      - autenticação
swagger: "2.0"
